repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: fb9fc7b71b63ea94e7cfb70f4351e9bddea181d3
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-vcs-permalinks
      - id: debug-statements
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: fix-encoding-pragma
      - id: mixed-line-ending
      - id: pretty-format-json
      - id: sort-simple-yaml
      - id: trailing-whitespace
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.4 # or specific git tag
    hooks:
      - id: forbid-binary
        exclude: >
          (?x)^(
            gradle/wrapper/gradle-wrapper.jar
          )$
      - id: git-dirty
  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.11.0
    hooks:
      - id: pretty-format-kotlin
        args: [--autofix]
        files: ^.*\.kts?$
