/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.3/userguide/building_java_projects.html
 */

// For `KotlinCompile` task below

plugins {
  kotlin("jvm") version "1.9.21" // Kotlin version to use
  application // Application plugin. Also see 1️⃣ below the code
}

group = "dev.miguely" // A company name, for example, `org.jetbrains`
version = "1.0" // Version to assign to the built artifact

repositories { // Sources of dependencies. See 2️⃣
  mavenCentral() // Maven Central Repository. See 3️⃣
}

dependencies { // All the libraries you want to use. See 4️⃣
  // Copy dependencies' names after you find them in a repository
  testImplementation(kotlin("test")) // The Kotlin test library
}

tasks.test { // See 5️⃣
  useJUnitPlatform() // JUnitPlatform for tests. See 6️⃣
}

kotlin { // Extension for easy setup
  jvmToolchain(19) // Target version of generated JVM bytecode. See 7️⃣
}

application {
  mainClass.set("MainKt") // The main class of the application
}
